### ISSUE TITLE
Tests should support local and remote daemons

### ISSUE THREAD

**Issue by micahyoung** [buildpacks/imgutil#34]
For a standard `pack` developer flow, I'd like to develop locally (on a MacOS workstation) and run tests quickly against a local daemon (e.g. Docker Desktop with Linux containers) and a remote daemon via `DOCKER_HOST` (e.g. local Windows VM running Docker Desktop with Windows containers). Other useful scenarios could be running tests against older daemons or Docker-in-Docker rootless daemons and be able to fix issues before committing/pushing.

This would also give some coverage for `DOCKER_HOST` functionality, which technically works though tests fail.

I'm interested in opening a PR to change the tests as follows:
* Change test image names from `localhost:<registry.Port>/random-image-name` to `<DOCKER_HOST ip>:<registry.Port>/random-image-name` only when `DOCKER_HOST` is set
* Change test registry containers to use HTTP Basic Auth, so CI containers won't be compromised - similar to `pack`'s tests.
* Change `remote` to query using test registry Basic Auth credentials. Two possible approaches:
  * Indirectly through `auth.DefaultKeychain` by setting `DOCKER_CONFIG` to point to a test config with `auths` containing creds which default keychain loads.
  * Explicitly by replacing changing each `remote.NewImage` to use a test keychain instead that loads the credentials.   
* Change `remote` to not push/pull to daemon, instead use `go-containerregistry` to directly work with manifests and images directly on the registry.

**Comment by micahyoung** [comment]
This is technically a nice-to-have for the Windows work, since we could for now just run `imgutil` tests on Windows workstation targetting a local Docker Desktop with Windows containers.

**Comment by ekcasey** [comment]
I agree that running against a remote docker daemon should be supported.

For the remote tests, I wonder if the registry should be configurable, rather than deployed to the docker daemon as part of the test code?  The repository could be supplied to the tests as an environment variable, and test images could be generated with randomized tags that are cleaned up afterwards. Credentials would need to be set prior to running the tests either in the default docker config json or in a docker config set with `DOCKER_CONFIG` (I believe both of these would work with the `authn.DefaultKeychain`).

Our CI scripts could deploy a registry to the daemon and set the credentials before running the tests.

**Comment by micahyoung** [comment]
Running against a remote daemon works now thanks to [docker_registry.go](https://github.com/buildpacks/imgutil/blob/52098da066399a82e53cd5dbf849d561684dcf37/testhelpers/docker_registry.go#L222-L224), so long as your `daemon.json` has an `insecure-registries` entry with a `<host ip>/32` set, where `<host ip>` is your `DOCKER_HOST=tcp://<host ip>`. 

#### Example:
Remote host's `daemon.json`
```json
{
  "insecure-registries": [
    "192.168.86.5/32"
  ]
}
```

Run tests:
```
export DOCKER_HOST=tcp://192.168.86.5:2375
make test
```


@ekcasey I think this can be closed as most of the other behavior you describe is implemented and if this setup is acceptable?
